module.exports = {
  RESET: "\x1b[0m",
  REFERENCE: "\x1b[33m",
  STATUS: "\x1b[94m",
  BOLD: "\x1b[1m",
  UNDERLINE: "\x1b[4m",
  PARAM: "\x1b[91m",
  PRIORITY: "\x1b[94m",
  COMMAND: "\x1b[95m",
  MODIFIER: "\x1b[92m",
  WARNING: "\x1b[33m",
  HIGH_PRIORITY: "\x1b[91m",
  MED_PRIORITY: "\x1b[33m",
  LOW_PRIORITY: "\x1b[92m",
  NOTE_NUMBER: "\x1b[91m",
  NOTE_DIRECTORY: "\x1b[93m",
  NOTE_CURRENT_DIRECTORY: "\x1b[94m",
  ROUTE_QUESTIONID: "\x1b[31m",
  ROUTE_CONDITION_TYPE: "\x1b[32m",
  ROUTE_COMPARISON_VALUE: "\x1b[33m",
  ROUTE_BEHAVIOUR_TYPE: "\x1b[34m",
  ROUTE_PAGE_SLUG: "\x1b[35m",
};
